package com.technischools.telegramApp.chatApi;

import com.theokanning.openai.completion.chat.ChatCompletionResult;
import com.theokanning.openai.completion.chat.ChatMessage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class ChatAPIController {
    private final ChatAPIService chatApiService;

    @Autowired
    public ChatAPIController(ChatAPIService chatApiService) {
        this.chatApiService = chatApiService;
    }

    /*
    * returns the full "response"/result object, generated by the API
    * */
    public ChatCompletionResult getChatResponseFromPrompt(String userPrompt) {
        return chatApiService.getChatResponse(userPrompt);
    }

    /*
    * extracts the message object from the response object
    * */
    public ChatMessage getMessageFromResponse(ChatCompletionResult chatResponse) {
        return chatResponse.getChoices().getFirst().getMessage();
    }

    /*
    * grabs the content of a message object
    * */
    public String getMessageContent(ChatMessage chatMessage) {
        return chatMessage.getContent();
    }

    /*
    * returns the amount of tokens used by the api to generate given response
    * */
    public long getTokensUsed(ChatCompletionResult chatResponse) {
        return chatResponse.getUsage().getCompletionTokens();
    }
}
